apiVersion: v1alpha1
kind: Role
metadata:
  name: bark-role-manage-bark
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Bark Management"
    rbac.authorization.halo.run/display-name: "Manage Bark"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:bark:bark:manage"]
rules:
  - apiGroups: ["console.api.bark.halo.run"]
    resources: ["bark/test"]
    verbs: ["create"]